---
title: "Untitled"
output: github_document
date: '`r format(Sys.time(), "%d %B, %Y")`'
bibliography: references.bib
knit: worcs::cite_all
---

```{r setup, include=FALSE}
library("worcs")
# We recommend that you prepare your raw data for analysis in 'prepare_data.R',
# and end that file with either open_data(yourdata), or closed_data(yourdata).
# Then, uncomment the line below to load the original or synthetic data
# (whichever is available), to allow anyone to reproduce your code:
# load_data()
knitr::opts_chunk$set(echo = TRUE)
# Setup for targets:

library(targets)
tar_config_set(store = "../_targets")
tar_load(tab_fits)
# You can interact with tar objects as usual, e.g.:
# print(model)
```

This manuscript uses the Workflow for Open Reproducible Code in Science [@vanlissaWORCSWorkflowOpen2021] to ensure reproducibility and transparency. All code <!--and data--> are available at <k99_ema>.

This is an example of a non-essential citation [@@vanlissaWORCSWorkflowOpen2021]. If you change the rendering function to `worcs::cite_essential`, it will be removed.


```{r tabfit}
knitr::kable(tab_fits)
```

